<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [Mono-bugs] [Bug 407987] New: &quot;catch&quot; does not work for used	defined exception
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:mono-bugs%40lists.ximian.com?Subject=%5BMono-bugs%5D%20%5BBug%20407987%5D%20New%3A%20%22catch%22%20does%20not%20work%20for%20used%0A%09defined%20exception&In-Reply-To=">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="076632.html">
   <LINK REL="Next"  HREF="077278.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Mono-bugs] [Bug 407987] New: &quot;catch&quot; does not work for used	defined exception</H1>
    <B>bugzilla_noreply at novell.com</B> 
    <A HREF="mailto:mono-bugs%40lists.ximian.com?Subject=%5BMono-bugs%5D%20%5BBug%20407987%5D%20New%3A%20%22catch%22%20does%20not%20work%20for%20used%0A%09defined%20exception&In-Reply-To="
       TITLE="[Mono-bugs] [Bug 407987] New: &quot;catch&quot; does not work for used	defined exception">bugzilla_noreply at novell.com
       </A><BR>
    <I>Thu Jul 10 10:54:29 EDT 2008</I>
    <P><UL>
        <LI>Previous message: <A HREF="076632.html">[Mono-bugs] [Bug 369670] [LINQ] Range varibles use parent scope
</A></li>
        <LI>Next message: <A HREF="077278.html">[Mono-bugs] [Bug 407987] &quot;catch&quot; does not work for used defined	exception
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#76633">[ date ]</a>
              <a href="thread.html#76633">[ thread ]</a>
              <a href="subject.html#76633">[ subject ]</a>
              <a href="author.html#76633">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE><A HREF="https://bugzilla.novell.com/show_bug.cgi?id=407987">https://bugzilla.novell.com/show_bug.cgi?id=407987</A>


           Summary: &quot;catch&quot; does not work for used defined exception
           Product: Mono: Debugger
           Version: unspecified
          Platform: Other
        OS/Version: Other
            Status: NEW
          Severity: Normal
          Priority: P5 - None
         Component: cli
        AssignedTo: <A HREF="http://lists.ximian.com/mailman/listinfo/mono-bugs">martin at novell.com</A>
        ReportedBy: <A HREF="http://lists.ximian.com/mailman/listinfo/mono-bugs">msafar at novell.com</A>
         QAContact: <A HREF="http://lists.ximian.com/mailman/listinfo/mono-bugs">mono-bugs at lists.ximian.com</A>
          Found By: ---


1. Create a project with a new exception type class.
2. run mdb
3. start
4. type &quot;catch &lt;&lt;your exception&gt;&gt;

(mdb) catch MyException
ERROR: Type `MyException' is not an exception type.


-- 
Configure bugmail: <A HREF="https://bugzilla.novell.com/userprefs.cgi?tab=email">https://bugzilla.novell.com/userprefs.cgi?tab=email</A>
------- You are receiving this mail because: -------
You are the QA contact for the bug.
</PRE>


















<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="076632.html">[Mono-bugs] [Bug 369670] [LINQ] Range varibles use parent scope
</A></li>
	<LI>Next message: <A HREF="077278.html">[Mono-bugs] [Bug 407987] &quot;catch&quot; does not work for used defined	exception
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#76633">[ date ]</a>
              <a href="thread.html#76633">[ thread ]</a>
              <a href="subject.html#76633">[ subject ]</a>
              <a href="author.html#76633">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://lists.ximian.com/mailman/listinfo/mono-bugs">More information about the mono-bugs
mailing list</a><br>
</body></html>
