<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [Mono-list] Threading + Exception Handling (2 Questions)
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:tpsoftware%40users.sourceforge.net">
   <META NAME="robots" CONTENT="index,nofollow">
   
   <LINK REL="Previous"  HREF="013053.html">
   <LINK REL="Next"  HREF="013086.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Mono-list] Threading + Exception Handling (2 Questions)
   </H1>
    <B>Timothy Parez
    </B> 
    <A HREF="mailto:tpsoftware%40users.sourceforge.net"
       TITLE="[Mono-list] Threading + Exception Handling (2 Questions)">tpsoftware@users.sourceforge.net
       </A><BR>
    <I>Thu, 20 Mar 2003 16:23:24 +0100</I>
    <P><UL>
        <LI> Previous message: <A HREF="013053.html">[Mono-list] Threading + Exception Handling (2 Questions)
</A></li>
        <LI> Next message: <A HREF="013086.html">[Mono-list] Tutorial/Example needed: Using Glade with GTK#
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#13054">[ date ]</a>
              <a href="thread.html#13054">[ thread ]</a>
              <a href="subject.html#13054">[ subject ]</a>
              <a href="author.html#13054">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>I thought I'd show you this result

Mono v0.23 (Windows) Output:

Main: Starting Worker
Worker Thread: Working...
Worker Thread: Problem.
Unhandled Exception:
  sender=
  e=
  ** UnhandledExceptionEventArgs is null?!
Generating New Exception

** (threading.exe:2460): WARNING **: exception inside UnhandledException
handler!
Main: Finished

.NET Output:

Main: Starting Worker
Worker Thread: Working...
Worker Thread: Problem.
Unhandled Exception:
  sender=Name: threading.exe
There are no context policies.

  e=System.UnhandledExceptionEventArgs
  e: System.UnhandledExceptionEventArgs
  Exception: System.Exception: Worker Thread Problem
   at R.Worker()
  IsTerminating: False
Generating New Exception
Main: Finished

So in 0.23 it's not yet fixed.
I'll try the linux version to see if it is fixed there.

Timothy.

----- Original Message -----
From: &quot;Jonathan Pryor&quot; &lt;<A HREF="mailto:jonpryor@vt.edu">jonpryor@vt.edu</A>&gt;
To: &quot;Timothy Parez&quot; &lt;<A HREF="mailto:tpsoftware@users.sourceforge.net">tpsoftware@users.sourceforge.net</A>&gt;
Cc: &quot;Mono List&quot; &lt;<A HREF="mailto:mono-list@ximian.com">mono-list@ximian.com</A>&gt;
Sent: Thursday, March 20, 2003 4:12 PM
Subject: Re: [Mono-list] Threading + Exception Handling (2 Questions)


&gt;<i> Responses Inline.
</I>&gt;<i>
</I>&gt;<i> On Thu, 2003-03-20 at 09:59, Timothy Parez wrote:
</I>&gt;<i> &lt;snip/&gt;
</I>&gt;<i> &gt; Is this implemented for mono under Linux ?
</I>&gt;<i>
</I>&gt;<i> Yes, Thread.Abort is implemented under Linux.
</I>&gt;<i>
</I>&gt;<i> &lt;snip/&gt;
</I>&gt;<i> &gt; Alas, this information appears to be null
</I>&gt;<i> &gt; &gt; &gt; for my build of mono (see attached sample program), but that might
</I>be
&gt;<i> &gt; &gt; &gt; fixed by now.  Anyone else know for sure?
</I>&gt;<i> &gt;
</I>&gt;<i> &gt; What version of mono are you using ?
</I>&gt;<i> &gt; I'm currently using mono 0.23 (red-carpet rpm)
</I>&gt;<i>
</I>&gt;<i> I'm using an ancient CVS build (mono --version reports 0.19.1.0).  I
</I>&gt;<i> really should update some time...
</I>&gt;<i>
</I>&gt;<i> &lt;snip/&gt;
</I>&gt;<i> &gt; Besides the solution you noted what do you think about
</I>&gt;<i> &gt; making the QueryBase class expose a custom event which the second
</I>&gt;<i> &gt; thread calls when an error occurs and which the first thread subscribes
</I>to.
&gt;<i> &gt; Or is that to far fetched, as it would involve a class subscribing to an
</I>&gt;<i> &gt; event
</I>&gt;<i> &gt; he exposed himself.
</I>&gt;<i>
</I>&gt;<i> That should be possible as well.  It's effectively the same thing.  It's
</I>&gt;<i> also the first idea that came to mind before I looked up the
</I>&gt;<i> UnhandledException event.
</I>&gt;<i>
</I>&gt;<i>  - Jon
</I>&gt;<i>
</I>&gt;<i> &gt; Thnx
</I>&gt;<i> &gt; Timothy.
</I>&gt;<i> &gt;
</I>&gt;<i> &gt; ----- Original Message -----
</I>&gt;<i> &gt; From: &quot;Jonathan Pryor&quot; &lt;<A HREF="mailto:jonpryor@vt.edu">jonpryor@vt.edu</A>&gt;
</I>&gt;<i> &gt; To: &quot;Timothy Parez&quot; &lt;<A HREF="mailto:tpsoftware@users.sourceforge.net">tpsoftware@users.sourceforge.net</A>&gt;
</I>&gt;<i> &gt; Cc: &quot;Mono List&quot; &lt;<A HREF="mailto:mono-list@ximian.com">mono-list@ximian.com</A>&gt;
</I>&gt;<i> &gt; Sent: Thursday, March 20, 2003 3:47 PM
</I>&gt;<i> &gt; Subject: Re: [Mono-list] Threading + Exception Handling (2 Questions)
</I>&gt;<i> &gt;
</I>&gt;<i> &gt;
</I>&gt;<i> &gt; &gt; Oops.  Forgot to attach the UnhandledException sample.
</I>&gt;<i> &gt; &gt;
</I>&gt;<i> &gt; &gt;  - Jon
</I>&gt;<i> &gt; &gt;
</I>&gt;<i> &gt; &gt; On Thu, 2003-03-20 at 09:45, Jonathan Pryor wrote:
</I>&gt;<i> &gt; &gt; &gt; It sounds like you want to have an exception generated in one thread
</I>&gt;<i> &gt; &gt; &gt; appear in another.  I don't think that's possible.  Exceptions are
</I>&gt;<i> &gt; &gt; &gt; relative to the thread they're generated from, and deal exclusively
</I>with
&gt;<i> &gt; &gt; &gt; the thread of that stack.
</I>&gt;<i> &gt; &gt; &gt;
</I>&gt;<i> &gt; &gt; &gt; However, there is a workaround, if I'm understanding you correctly.
</I>You
&gt;<i> &gt; &gt; &gt; could hook up the AppDomain.UnhandledException event to your first
</I>&gt;<i> &gt; &gt; &gt; thread, which would let you know if an exception was thrown from
</I>some
&gt;<i> &gt; &gt; &gt; thread in your application and not caught.
</I>&gt;<i> &gt; &gt; &gt;
</I>&gt;<i> &gt; &gt; &gt; In theory, you could use the UnhandledExceptionEventArgs information
</I>to
&gt;<i> &gt; &gt; &gt; determine the type of the thrown exception, to ensure that you're
</I>&gt;<i> &gt; &gt; &gt; trapping the right errors.  Alas, this information appears to be
</I>null
&gt;<i> &gt; &gt; &gt; for my build of mono (see attached sample program), but that might
</I>be
&gt;<i> &gt; &gt; &gt; fixed by now.  Anyone else know for sure?
</I>&gt;<i> &gt; &gt; &gt;
</I>&gt;<i> &gt; &gt; &gt; Regardless, your UnhandledException handler can set a variable which
</I>the
&gt;<i> &gt; &gt; &gt; main thread checks.  If the variable is set, the main thread would
</I>throw
&gt;<i> &gt; &gt; &gt; an exception, simulating the appearance of the thread moving from
</I>one
&gt;<i> &gt; &gt; &gt; thread to another.
</I>&gt;<i> &gt; &gt; &gt;
</I>&gt;<i> &gt; &gt; &gt; As for Thread.Abort, it should work as you expect.  Thread.Abort
</I>&gt;<i> &gt; &gt; &gt; generates an exception in the specified thread, not the calling
</I>thread
&gt;<i> &gt; &gt; &gt; (unless they're the same), and that exception will have no effect on
</I>the
&gt;<i> &gt; &gt; &gt; calling thread.  So Thread.Abort followed by a throw should work.
</I>&gt;<i> &gt; &gt; &gt;
</I>&gt;<i> &gt; &gt; &gt; There is one problem, though.  Thread.Abort isn't implemented for
</I>mono
&gt;<i> &gt; &gt; &gt; under Windows (it's a pthread under Windows problem; check the
</I>&gt;<i> &gt; &gt; &gt; archives), so this may not be an acceptable solution for you.
</I>&gt;<i> &gt; &gt; &gt;
</I>&gt;<i> &gt; &gt; &gt;  - Jon
</I>&gt;<i> &gt; &gt; &gt;
</I>&gt;<i> &gt; &gt; &gt; On Thu, 2003-03-20 at 08:51, Timothy Parez wrote:
</I>&gt;<i> &gt; &gt; &gt; &gt; Hello,
</I>&gt;<i> &gt; &gt; &gt; &gt;
</I>&gt;<i> &gt; &gt; &gt; &gt; I have class which creates another thread
</I>&gt;<i> &gt; &gt; &gt; &gt; now that other tread can throw a custom error, but
</I>&gt;<i> &gt; &gt; &gt; &gt; when this error is thrown I want the main thread of the class
</I>library
&gt;<i> &gt; &gt; &gt; &gt; to receive this exception so that the client application which
</I>uses my
&gt;<i> &gt; &gt; &gt; &gt; library get's this error and all execution of other code in my
</I>class
&gt;<i> &gt; &gt; &gt; &gt; library is stopped.
</I>&gt;<i> &gt; &gt; &gt; &gt;
</I>&gt;<i> &gt; &gt; &gt; &gt;  //Code executed by the main thread:
</I>&gt;<i> &gt; &gt; &gt; &gt;   protected byte[] Query(byte[] sendData)
</I>&gt;<i> &gt; &gt; &gt; &gt;   {
</I>&gt;<i> &gt; &gt; &gt; &gt;    //Set all values
</I>&gt;<i> &gt; &gt; &gt; &gt;    data = sendData;
</I>&gt;<i> &gt; &gt; &gt; &gt;
</I>&gt;<i> &gt; &gt; &gt; &gt;    queryThread = new Thread(new ThreadStart(ExecuteQuery));
</I>&gt;<i> &gt; &gt; &gt; &gt;
</I>&gt;<i> &gt; &gt; &gt; &gt;    //Start the query
</I>&gt;<i> &gt; &gt; &gt; &gt;    queryThread.Start();
</I>&gt;<i> &gt; &gt; &gt; &gt;
</I>&gt;<i> &gt; &gt; &gt; &gt;    //Wait for the query to exit
</I>&gt;<i> &gt; &gt; &gt; &gt;    if (!queryThread.Join(timeout * 1000))
</I>&gt;<i> &gt; &gt; &gt; &gt;    {
</I>&gt;<i> &gt; &gt; &gt; &gt;     queryThread.Abort();
</I>&gt;<i> &gt; &gt; &gt; &gt;     throw new Exceptions.QueryTimeoutException(&quot;Query Timeout: &quot; +
</I>&gt;<i> &gt; &gt; &gt; &gt; timeout.ToString() + &quot; seconds&quot;);
</I>&gt;<i> &gt; &gt; &gt; &gt;    }
</I>&gt;<i> &gt; &gt; &gt; &gt;
</I>&gt;<i> &gt; &gt; &gt; &gt;    //Return the response, which is now saved in the local variable
</I>&gt;<i> &gt; &gt; &gt; &gt;    return queryResponse;
</I>&gt;<i> &gt; &gt; &gt; &gt;   }
</I>&gt;<i> &gt; &gt; &gt; &gt;
</I>&gt;<i> &gt; &gt; &gt; &gt; // Code executed by the queryThread
</I>&gt;<i> &gt; &gt; &gt; &gt;  private void ExecuteQuery()
</I>&gt;<i> &gt; &gt; &gt; &gt;   {
</I>&gt;<i> &gt; &gt; &gt; &gt;    UdpClient client = new UdpClient();
</I>&gt;<i> &gt; &gt; &gt; &gt;    //Connect to the server and send the query data
</I>&gt;<i> &gt; &gt; &gt; &gt;    try
</I>&gt;<i> &gt; &gt; &gt; &gt;    {
</I>&gt;<i> &gt; &gt; &gt; &gt;     client.Connect(ip,port);
</I>&gt;<i> &gt; &gt; &gt; &gt;     client.Send(data,data.Length);
</I>&gt;<i> &gt; &gt; &gt; &gt;    }
</I>&gt;<i> &gt; &gt; &gt; &gt;    catch (Exception e)
</I>&gt;<i> &gt; &gt; &gt; &gt;    {
</I>&gt;<i> &gt; &gt; &gt; &gt;     client.Close();
</I>&gt;<i> &gt; &gt; &gt; &gt;     throw new Exceptions.InvalidHostException(&quot;Unknown host: &quot; +
</I>&gt;<i> &gt; &gt; &gt; &gt; ip,e);
</I>&gt;<i> &gt; &gt; &gt; &gt;    }
</I>&gt;<i> &gt; &gt; &gt; &gt;
</I>&gt;<i> &gt; &gt; &gt; &gt;    //Listen for a response - This is the client side
</I>&gt;<i> &gt; &gt; &gt; &gt;    IPEndPoint serverIPEndPoint = new IPEndPoint(IPAddress.Any,0);
</I>&gt;<i> &gt; &gt; &gt; &gt;
</I>&gt;<i> &gt; &gt; &gt; &gt;    //Receive the response
</I>&gt;<i> &gt; &gt; &gt; &gt;    try
</I>&gt;<i> &gt; &gt; &gt; &gt;    {
</I>&gt;<i> &gt; &gt; &gt; &gt;     queryResponse = client.Receive(ref serverIPEndPoint);
</I>&gt;<i> &gt; &gt; &gt; &gt;    }
</I>&gt;<i> &gt; &gt; &gt; &gt;    catch (Exception e)
</I>&gt;<i> &gt; &gt; &gt; &gt;    {
</I>&gt;<i> &gt; &gt; &gt; &gt;     throw new Exceptions.ConnectionRefusedException(&quot;The
</I>connection
&gt;<i> &gt; &gt; &gt; &gt; was refused by the remote host: &quot; + ip + &quot;:&quot; + port.ToString(),e);
</I>&gt;<i> &gt; &gt; &gt; &gt;    }
</I>&gt;<i> &gt; &gt; &gt; &gt;    finally
</I>&gt;<i> &gt; &gt; &gt; &gt;    {
</I>&gt;<i> &gt; &gt; &gt; &gt;     client.Close();
</I>&gt;<i> &gt; &gt; &gt; &gt;    }
</I>&gt;<i> &gt; &gt; &gt; &gt;   }
</I>&gt;<i> &gt; &gt; &gt; &gt;
</I>&gt;<i> &gt; &gt; &gt; &gt; As you can see the ExecuteQuery() function can throw the
</I>&gt;<i> &gt; &gt; &gt; &gt; Exceptions.ConnectionRefusedException,
</I>&gt;<i> &gt; &gt; &gt; &gt; but my main thread never receives this error, so the execution of
</I>the
&gt;<i> &gt; &gt; &gt; &gt; code in the main thread does not stop.
</I>&gt;<i> &gt; &gt; &gt; &gt; How can I fix this.
</I>&gt;<i> &gt; &gt; &gt; &gt;
</I>&gt;<i> &gt; &gt; &gt; &gt; I also have a second question:
</I>&gt;<i> &gt; &gt; &gt; &gt;     queryThread.Abort();
</I>&gt;<i> &gt; &gt; &gt; &gt;     throw new Exceptions.QueryTimeoutException(&quot;Query Timeout: &quot; +
</I>&gt;<i> &gt; &gt; &gt; &gt; timeout.ToString() + &quot; seconds&quot;);
</I>&gt;<i> &gt; &gt; &gt; &gt; I abort the second thread, will the QueryTimeoutException still be
</I>&gt;<i> &gt; &gt; &gt; &gt; thrown ? (I hope so), or will the .Abort() cause an error
</I>&gt;<i> &gt; &gt; &gt; &gt; which will prevent from the QueryTimeoutException ever happening,
</I>in
&gt;<i> &gt; &gt; &gt; &gt; that case how do I abort the second query and still throw the
</I>&gt;<i> &gt; &gt; &gt; &gt; QueryTimeoutException ?
</I>&gt;<i> &gt; &gt; &gt; &gt;
</I>&gt;<i> &gt; &gt; &gt; &gt;
</I>&gt;<i> &gt; &gt; &gt; &gt; Thnx.
</I>&gt;<i> &gt; &gt; &gt; &gt; TP.
</I>&gt;<i> &gt; &gt; &gt;
</I>&gt;<i> &gt; &gt; &gt; _______________________________________________
</I>&gt;<i> &gt; &gt; &gt; Mono-list maillist  -  <A HREF="mailto:Mono-list@lists.ximian.com">Mono-list@lists.ximian.com</A>
</I>&gt;<i> &gt; &gt; &gt; <A HREF="http://lists.ximian.com/mailman/listinfo/mono-list">http://lists.ximian.com/mailman/listinfo/mono-list</A>
</I>&gt;<i> &gt; &gt;
</I>&gt;<i> &gt;
</I>&gt;<i> &gt; _______________________________________________
</I>&gt;<i> &gt; Mono-list maillist  -  <A HREF="mailto:Mono-list@lists.ximian.com">Mono-list@lists.ximian.com</A>
</I>&gt;<i> &gt; <A HREF="http://lists.ximian.com/mailman/listinfo/mono-list">http://lists.ximian.com/mailman/listinfo/mono-list</A>
</I>&gt;<i>
</I>&gt;<i> _______________________________________________
</I>&gt;<i> Mono-list maillist  -  <A HREF="mailto:Mono-list@lists.ximian.com">Mono-list@lists.ximian.com</A>
</I>&gt;<i> <A HREF="http://lists.ximian.com/mailman/listinfo/mono-list">http://lists.ximian.com/mailman/listinfo/mono-list</A>
</I>

</PRE>
<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI> Previous message: <A HREF="013053.html">[Mono-list] Threading + Exception Handling (2 Questions)
</A></li>
	<LI> Next message: <A HREF="013086.html">[Mono-list] Tutorial/Example needed: Using Glade with GTK#
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#13054">[ date ]</a>
              <a href="thread.html#13054">[ thread ]</a>
              <a href="subject.html#13054">[ subject ]</a>
              <a href="author.html#13054">[ author ]</a>
         </LI>
       </UL>
</body></html>
