<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [Mono-bugs] [Bug 463568] New: Dynamic method stacks don't unwind	properly
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:mono-bugs%40lists.ximian.com?Subject=%5BMono-bugs%5D%20%5BBug%20463568%5D%20New%3A%20Dynamic%20method%20stacks%20don%27t%20unwind%0A%09properly&In-Reply-To=">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="084112.html">
   <LINK REL="Next"  HREF="084119.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Mono-bugs] [Bug 463568] New: Dynamic method stacks don't unwind	properly</H1>
    <B>bugzilla_noreply at novell.com</B> 
    <A HREF="mailto:mono-bugs%40lists.ximian.com?Subject=%5BMono-bugs%5D%20%5BBug%20463568%5D%20New%3A%20Dynamic%20method%20stacks%20don%27t%20unwind%0A%09properly&In-Reply-To="
       TITLE="[Mono-bugs] [Bug 463568] New: Dynamic method stacks don't unwind	properly">bugzilla_noreply at novell.com
       </A><BR>
    <I>Mon Jan  5 10:07:02 EST 2009</I>
    <P><UL>
        <LI>Previous message: <A HREF="084112.html">[Mono-bugs] [Bug 442105] XSP2.0.1 on Windows crashes when exiting [ assert in mono_get_lmf_addr]
</A></li>
        <LI>Next message: <A HREF="084119.html">[Mono-bugs] [Bug 463568] Dynamic method stacks don't unwind properly
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#84113">[ date ]</a>
              <a href="thread.html#84113">[ thread ]</a>
              <a href="subject.html#84113">[ subject ]</a>
              <a href="author.html#84113">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE><A HREF="https://bugzilla.novell.com/show_bug.cgi?id=463568">https://bugzilla.novell.com/show_bug.cgi?id=463568</A>


           Summary: Dynamic method stacks don't unwind properly
           Product: Mono: Runtime
           Version: SVN
          Platform: x86-64
        OS/Version: Linux
            Status: NEW
          Severity: Minor
          Priority: P5 - None
         Component: JIT
        AssignedTo: <A HREF="http://lists.ximian.com/mailman/listinfo/mono-bugs">lupus at novell.com</A>
        ReportedBy: <A HREF="http://lists.ximian.com/mailman/listinfo/mono-bugs">Dax at daxxfiles.net</A>
         QAContact: <A HREF="http://lists.ximian.com/mailman/listinfo/mono-bugs">mono-bugs at lists.ximian.com</A>
          Found By: ---


Description of Problem:
When throwing exceptions in dynamic method, the callstack does not unwind
properly: only one dynamic method is unwound, more specifically the one method
used to enter the dm-stack.

Steps to reproduce the problem:
compile and run:

using System.Reflection;
using System.Reflection.Emit;
using System;

class test
{
  static void Main()
  {
    var dm = new DynamicMethod(&quot;foo.a&quot;, typeof(void), Type.EmptyTypes,
                               typeof(test));
    var il = dm.GetILGenerator();
    il.ThrowException(typeof(Exception));

    var dm3 = new DynamicMethod(&quot;foo.b&quot;, typeof(void), Type.EmptyTypes,
                                typeof(test));
    il = dm3.GetILGenerator();
    il.Emit(OpCodes.Call, dm);
    il.Emit(OpCodes.Ret);

    var dm2 = new DynamicMethod(&quot;foo.c&quot;, typeof(void), Type.EmptyTypes,
                                typeof(test));
    il = dm2.GetILGenerator();
    il.Emit(OpCodes.Call, dm3);
    il.Emit(OpCodes.Ret);

    var action = (Action)dm2.CreateDelegate(typeof(Action));
    try {
      action();
    } catch(Exception e) {
      Console.WriteLine(e);
    }
  }
}


Actual Results:

System.Exception: Exception of type 'System.Exception' was thrown.
at (wrapper dynamic-method) test.foo.c () &lt;0x00014&gt;
at test.Main () &lt;0x00213&gt;


Expected Results:


System.Exception: Exception of type 'System.Exception' was thrown.
at (wrapper dynamic-method) test.foo.a () &lt;0x00029&gt;
at (wrapper dynamic-method) test.foo.b () &lt;0x00014&gt;
at (wrapper dynamic-method) test.foo.c () &lt;0x00014&gt;
at test.Main () &lt;0x00213&gt;


How often does this happen? 

Every time.


Additional Information:

Oddly, wrapping the code of each an every dynamic method in try { } (no
catch/finally) produces the expected output. Is this by design or rather a
minor bug, as regular method work just fine?


-- 
Configure bugmail: <A HREF="https://bugzilla.novell.com/userprefs.cgi?tab=email">https://bugzilla.novell.com/userprefs.cgi?tab=email</A>
------- You are receiving this mail because: -------
You are the QA contact for the bug.
</PRE>



















<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="084112.html">[Mono-bugs] [Bug 442105] XSP2.0.1 on Windows crashes when exiting [ assert in mono_get_lmf_addr]
</A></li>
	<LI>Next message: <A HREF="084119.html">[Mono-bugs] [Bug 463568] Dynamic method stacks don't unwind properly
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#84113">[ date ]</a>
              <a href="thread.html#84113">[ thread ]</a>
              <a href="subject.html#84113">[ subject ]</a>
              <a href="author.html#84113">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://lists.ximian.com/mailman/listinfo/mono-bugs">More information about the mono-bugs
mailing list</a><br>
</body></html>
