<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [Mono-bugs] [Bug 572630] New: AsyncCompletedEventArgs.Error always null when handling SmtpClient.SendCompleted
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:mono-bugs%40lists.ximian.com?Subject=%5BMono-bugs%5D%20%5BBug%20572630%5D%20New%3A%20AsyncCompletedEventArgs.Error%20always%0A%20null%20when%20handling%20SmtpClient.SendCompleted&In-Reply-To=">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="096732.html">
   <LINK REL="Next"  HREF="096744.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Mono-bugs] [Bug 572630] New: AsyncCompletedEventArgs.Error always null when handling SmtpClient.SendCompleted</H1>
    <B>bugzilla_noreply at novell.com</B> 
    <A HREF="mailto:mono-bugs%40lists.ximian.com?Subject=%5BMono-bugs%5D%20%5BBug%20572630%5D%20New%3A%20AsyncCompletedEventArgs.Error%20always%0A%20null%20when%20handling%20SmtpClient.SendCompleted&In-Reply-To="
       TITLE="[Mono-bugs] [Bug 572630] New: AsyncCompletedEventArgs.Error always null when handling SmtpClient.SendCompleted">bugzilla_noreply at novell.com
       </A><BR>
    <I>Thu Jan 21 06:26:10 EST 2010</I>
    <P><UL>
        <LI>Previous message: <A HREF="096732.html">[Mono-bugs] [Bug 548346] [SIM] objc_msgSend_stret which returns a struct containing a double does a ret $0x4 leaving the stack misaigned
</A></li>
        <LI>Next message: <A HREF="096744.html">[Mono-bugs] [Bug 572630] AsyncCompletedEventArgs.Error always null when handling SmtpClient.SendCompleted
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#96733">[ date ]</a>
              <a href="thread.html#96733">[ thread ]</a>
              <a href="subject.html#96733">[ subject ]</a>
              <a href="author.html#96733">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE><A HREF="http://bugzilla.novell.com/show_bug.cgi?id=572630">http://bugzilla.novell.com/show_bug.cgi?id=572630</A>

<A HREF="http://bugzilla.novell.com/show_bug.cgi?id=572630#c0">http://bugzilla.novell.com/show_bug.cgi?id=572630#c0</A>


           Summary: AsyncCompletedEventArgs.Error always null when
                    handling SmtpClient.SendCompleted
    Classification: Mono
           Product: Mono: Class Libraries
           Version: 2.6.x
          Platform: All
        OS/Version: Ubuntu
            Status: NEW
          Severity: Normal
          Priority: P5 - None
         Component: System
        AssignedTo: <A HREF="http://lists.ximian.com/mailman/listinfo/mono-bugs">mono-bugs at lists.ximian.com</A>
        ReportedBy: <A HREF="http://lists.ximian.com/mailman/listinfo/mono-bugs">dpldobrev at yahoo.com</A>
         QAContact: <A HREF="http://lists.ximian.com/mailman/listinfo/mono-bugs">mono-bugs at lists.ximian.com</A>
          Found By: ---
           Blocker: ---


Created an attachment (id=337950)
 --&gt; (<A HREF="http://bugzilla.novell.com/attachment.cgi?id=337950">http://bugzilla.novell.com/attachment.cgi?id=337950</A>)
Contributed under the MIT license; explained in &quot;Additional Information&quot;

User-Agent:       Mozilla/5.0 (Windows; U; Windows NT 6.1; bg; rv:1.9.1.7)
Gecko/20091221 Firefox/3.5.7

When sending an asynchronous e-mail with SmtpClient.SendAsync and handling
SmtpClient.SendCompletedd, the Error property of the AsyncCompletedEventArgs
object in the event handler is always null. However, it should be null only if
there was no error (that is, the e-mail was successfully sent). Otherwise
AsyncCompletedEventArgs.Error should contain the exception that occurred.

Reproducible: Always

Steps to Reproduce:
1. Add an event handler for the SmtpClient.SendCompleted event;
2. Deliberately configure the SmtpClient object (host, port, etc.) incorrectly;
3. Try to send an e-mail using SmtpClient.SendAsync;
Actual Results:  
The sending of the e-mail is not successful and the Error property of the
AsyncCompletedEventArgs object in the handler is null.

Expected Results:  
The sending of the e-mail is not successful and the Error property of the
AsyncCompletedEventArgs object in the handler contains the error that occurred.

The problem is in the SmtpClient.SendAsync method. It uses a BackgroungWorker
which internally catches any exceptions thrown by its OnDoWork method:

void ProcessWorker (object argument, AsyncOperation async, SendOrPostCallback
callback)
        {
            // do worker
            Exception error = null;
            DoWorkEventArgs e = new DoWorkEventArgs (argument);
            try {
                OnDoWork (e);
            } catch (Exception ex) {
                error = ex;
                e.Cancel = false;
            }
            callback (new object [] {
                new RunWorkerCompletedEventArgs (
                    e.Result, error, e.Cancel),
                async});
        }

However, SmtpClient.SendAsync also catches any exceptions in its handler for
DoWork:

public void SendAsync (MailMessage message, object userToken)
        {
            if (worker != null)
                throw new InvalidOperationException (&quot;Another SendAsync
operation is in progress&quot;);

            worker = new BackgroundWorker ();
            worker.DoWork += delegate (object o, DoWorkEventArgs ea) {
                try {
                    user_async_state = ea.Argument;
                    Send (message);
                } catch (Exception ex) {
                    ea.Result = ex;
                }
            };
            worker.WorkerSupportsCancellation = true;
            worker.RunWorkerCompleted += delegate (object o,
RunWorkerCompletedEventArgs ea) {
                // Note that RunWorkerCompletedEventArgs.UserState cannot be
used (LAMESPEC)
                OnSendCompleted (new AsyncCompletedEventArgs (ea.Error,
ea.Cancelled, user_async_state));
            };
            worker.RunWorkerAsync (userToken);
        }

Thus, the thrown exception never reaches BackgroungWorker.ProcessWorker which
causes the local variable of &quot;error&quot; to always equal null, and the
RunWorkerCompletedEventArgs always receives null for the error in its
constructor, and from there the AsyncCompletedEventArgs object constructed in
SmtpClient.SendAsync always has its Error property equal to null.

My proposed solution, contained in the attached patch, simply rethrows the
exception caught in SmtpClient.SendAsync which enables the error to reach the
BackgroundWorker and be handled there.

-- 
Configure bugmail: <A HREF="http://bugzilla.novell.com/userprefs.cgi?tab=email">http://bugzilla.novell.com/userprefs.cgi?tab=email</A>
------- You are receiving this mail because: -------
You are the QA contact for the bug.
You are the assignee for the bug.
</PRE>
















<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="096732.html">[Mono-bugs] [Bug 548346] [SIM] objc_msgSend_stret which returns a struct containing a double does a ret $0x4 leaving the stack misaigned
</A></li>
	<LI>Next message: <A HREF="096744.html">[Mono-bugs] [Bug 572630] AsyncCompletedEventArgs.Error always null when handling SmtpClient.SendCompleted
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#96733">[ date ]</a>
              <a href="thread.html#96733">[ thread ]</a>
              <a href="subject.html#96733">[ subject ]</a>
              <a href="author.html#96733">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://lists.ximian.com/mailman/listinfo/mono-bugs">More information about the mono-bugs
mailing list</a><br>
</body></html>
