<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [Mono-bugs] [Bug 76996][Nor] Changed - Inconsistent behaviour on
	PPC when throwing an exception in a finally block
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:mono-bugs%40lists.ximian.com?Subject=%5BMono-bugs%5D%20%5BBug%2076996%5D%5BNor%5D%20Changed%20-%20Inconsistent%20behaviour%20on%0A%09PPC%20when%20throwing%20an%20exception%20in%20a%20finally%20block&In-Reply-To=bug-76996%40chernobyl.ximian.com">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="037580.html">
   <LINK REL="Next"  HREF="037583.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Mono-bugs] [Bug 76996][Nor] Changed - Inconsistent behaviour on
	PPC when throwing an exception in a finally block</H1>
    <B>bugzilla-daemon at bugzilla.ximian.com</B> 
    <A HREF="mailto:mono-bugs%40lists.ximian.com?Subject=%5BMono-bugs%5D%20%5BBug%2076996%5D%5BNor%5D%20Changed%20-%20Inconsistent%20behaviour%20on%0A%09PPC%20when%20throwing%20an%20exception%20in%20a%20finally%20block&In-Reply-To=bug-76996%40chernobyl.ximian.com"
       TITLE="[Mono-bugs] [Bug 76996][Nor] Changed - Inconsistent behaviour on
	PPC when throwing an exception in a finally block">bugzilla-daemon at bugzilla.ximian.com
       </A><BR>
    <I>Wed Dec 28 14:38:39 EST 2005</I>
    <P><UL>
        <LI>Previous message: <A HREF="037580.html">[Mono-bugs] [Bug 77112][Nor] Changed - [PATCH ]
	XmlAttributes.XmlDefaultValue should be null and XmlIgnore fix
</A></li>
        <LI>Next message: <A HREF="037583.html">[Mono-bugs] [Bug 77113][Nor] New - Crash while browsing a derived
	class file
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#37582">[ date ]</a>
              <a href="thread.html#37582">[ thread ]</a>
              <a href="subject.html#37582">[ subject ]</a>
              <a href="author.html#37582">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Please do not reply to this email- if you want to comment on the bug, go to the
URL shown below and enter your comments there.

Changed by <A HREF="http://lists.ximian.com/mailman/listinfo/mono-bugs">vargaz at gmail.com.</A>

<A HREF="http://bugzilla.ximian.com/show_bug.cgi?id=76996">http://bugzilla.ximian.com/show_bug.cgi?id=76996</A>

--- shadow/76996	2005-12-20 10:26:16.000000000 -0500
+++ shadow/76996.tmp.6289	2005-12-28 14:38:38.000000000 -0500
@@ -81,6 +81,43 @@
 ------- Additional Comments From <A HREF="http://lists.ximian.com/mailman/listinfo/mono-bugs">robertj at gmx.net</A>  2005-12-14 16:21 -------
 &quot;foo&quot; cannot be reported, because the outer catch block
 never sees this exception. This is by design.
 
 Removed &quot;x86&quot; from the subject and changed the prio to &quot;normal&quot;.
 
+
+------- Additional Comments From <A HREF="http://lists.ximian.com/mailman/listinfo/mono-bugs">vargaz at gmail.com</A>  2005-12-28 14:38 -------
+I think this is similar to:
+
+<A HREF="http://bugzilla.ximian.com/show_bug.cgi?id=76388">http://bugzilla.ximian.com/show_bug.cgi?id=76388</A>
+
+The problem is that the finally clauses are called by the exception
+handling code through a trampoline, so when an exception is thrown 
+from the finally clause, the stack contains frames for the call_finally
+trampoline, mono_handle_exception () etc. The exception handling code
+doesn't have unwind info for these, and there is no LMF between the
+trampoline and the finally handler, so it is converted to an unhandled
+exception. Another problem is this code:
+
+   try {
+        try {
+            throw new Exception ();
+        }
+        finally {
+            throw new Exception ();
+        }
+   }
+   catch (Exception ex) {
+      return ...
+   }
+
+When the exception is thrown from the finally clause, it is caught by
+the outer catch handler which returns from the method, but the caller
+of this frame is not a normal method, but the call_finally trampoline,
+which uses an entirely different calling convention to call the
+finally code, so for example, if the method returns a structure, the
+register/stack slot holding the vtype pointer might not be set, or if
+the caller needs to do stack cleanup, the finally trampoline does not
+do it. etc.
+
+
+
</PRE>


<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="037580.html">[Mono-bugs] [Bug 77112][Nor] Changed - [PATCH ]
	XmlAttributes.XmlDefaultValue should be null and XmlIgnore fix
</A></li>
	<LI>Next message: <A HREF="037583.html">[Mono-bugs] [Bug 77113][Nor] New - Crash while browsing a derived
	class file
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#37582">[ date ]</a>
              <a href="thread.html#37582">[ thread ]</a>
              <a href="subject.html#37582">[ subject ]</a>
              <a href="author.html#37582">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://lists.ximian.com/mailman/listinfo/mono-bugs">More information about the mono-bugs
mailing list</a><br>
</body></html>
