<tt>
Yes&nbsp;this&nbsp;would&nbsp;be&nbsp;ideal&nbsp;...&nbsp;but&nbsp;not&nbsp;in&nbsp;case&nbsp;of&nbsp;client&nbsp;channel&nbsp;sink.&nbsp;When&nbsp;I&nbsp;get&nbsp;asyn&nbsp;response&nbsp;from&nbsp;the&nbsp;server&nbsp;AsyncProcessResponse&nbsp;is&nbsp;called,&nbsp;There&nbsp;I&nbsp;need&nbsp;to&nbsp;perform&nbsp;some&nbsp;operations&nbsp;and&nbsp;call&nbsp;next&nbsp;sink&nbsp;to&nbsp;process&nbsp;the&nbsp;message&nbsp;with:&lt;br&nbsp;/&gt;nextSink.AsyncProcessRequests()&nbsp;however&nbsp;this&nbsp;doesn't&nbsp;return&nbsp;any&nbsp;state&nbsp;at&nbsp;all&nbsp;:(&nbsp;and&nbsp;I&nbsp;don't&nbsp;have&nbsp;access&nbsp;to&nbsp;any&nbsp;methods&nbsp;that&nbsp;would&nbsp;End&nbsp;this&nbsp;processing&nbsp;(a'la&nbsp;EndInvoke)&lt;br&nbsp;/&gt;&lt;br&nbsp;/&gt;&lt;br&nbsp;/&gt;<br>
&lt;blockquote&nbsp;style=&quot;padding-left:&nbsp;1em;&nbsp;margin-left:&nbsp;1em;&nbsp;margin-bottom:0px;&nbsp;border-left:&nbsp;#ccc&nbsp;2px&nbsp;solid;&quot;&gt;<br>
&lt;div&nbsp;id=&quot;msg&quot;&gt;<br>
&lt;div&nbsp;id=&quot;msg-body&quot;&gt;<br>
&lt;div&nbsp;dir=&quot;ltr&quot;&gt;Typically&nbsp;you&nbsp;do&nbsp;something&nbsp;like&nbsp;this:&lt;br&nbsp;/&gt;&lt;br&nbsp;/&gt;1)&nbsp;Create&nbsp;a&nbsp;class&nbsp;like:&lt;br&nbsp;/&gt;&lt;br&nbsp;/&gt;public&nbsp;class&nbsp;MyAsyncResult&nbsp;:&nbsp;AsyncReult&lt;br&nbsp;/&gt;{&lt;br&nbsp;/&gt;&nbsp;internal&nbsp;Exception&nbsp;SavedException;&lt;br&nbsp;/&gt;}&lt;br&nbsp;/&gt;&lt;br&nbsp;/&gt;2)&nbsp;When&nbsp;the&nbsp;user&nbsp;starts&nbsp;an&nbsp;asyncronous&nbsp;request,&nbsp;instantiate&nbsp;one&nbsp;of&nbsp;those&nbsp;classes&nbsp;and&nbsp;return&nbsp;it&nbsp;as&nbsp;the&nbsp;IAsyncResult.&lt;br&nbsp;/&gt;3)&nbsp;Keep&nbsp;a&nbsp;reference&nbsp;to&nbsp;this&nbsp;object&nbsp;during&nbsp;your&nbsp;asynchronous&nbsp;processing&lt;br&nbsp;/&gt;4)&nbsp;If&nbsp;an&nbsp;exception&nbsp;is&nbsp;thrown,&nbsp;store&nbsp;it&nbsp;in&nbsp;the&nbsp;SavedException&nbsp;property&nbsp;and&nbsp;complete&nbsp;the&nbsp;request&nbsp;(typically&nbsp;set&nbsp;AsyncResult.Complete&nbsp;=true,&nbsp;signal&nbsp;the&nbsp;wait&nbsp;handle&nbsp;and&nbsp;invoke&nbsp;the&nbsp;AsyncCallback&nbsp;if&nbsp;one&nbsp;was&nbsp;supplied)&lt;br&nbsp;/&gt;5)&nbsp;This&nbsp;should&nbsp;result&nbsp;in&nbsp;the&nbsp;user&nbsp;calling&nbsp;the&nbsp;EndXXX&nbsp;method&nbsp;and&nbsp;pass&nbsp;in&nbsp;the&nbsp;IAsyncResult&nbsp;that&nbsp;you&nbsp;created&nbsp;at&nbsp;the&nbsp;start&lt;br&nbsp;/&gt;6)&nbsp;Just&nbsp;check&nbsp;if&nbsp;SavedException&nbsp;!=&nbsp;null,&nbsp;and&nbsp;if&nbsp;that's&nbsp;true,&nbsp;rethrow&nbsp;the&nbsp;exception&lt;br&nbsp;/&gt;&lt;br&nbsp;/&gt;&lt;/div&gt;<br>
&lt;/div&gt;<br>
&lt;/div&gt;<br>
&lt;/blockquote&gt;
</tt>
