<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [Mono-bugs] [Bug 542068] New: Using Mono2.4 Add-On, Process Dies because of Uncatchable exception during Ldap Connect in MultiThreaded environment
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:mono-bugs%40lists.ximian.com?Subject=%5BMono-bugs%5D%20%5BBug%20542068%5D%20New%3A%20Using%20Mono2.4%20Add-On%2C%0A%20Process%20Dies%20because%20of%20Uncatchable%20exception%20during%20Ldap%20Connect%0A%20in%20MultiThreaded%20environment&In-Reply-To=">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="093127.html">
   <LINK REL="Next"  HREF="093010.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Mono-bugs] [Bug 542068] New: Using Mono2.4 Add-On, Process Dies because of Uncatchable exception during Ldap Connect in MultiThreaded environment</H1>
    <B>bugzilla_noreply at novell.com</B> 
    <A HREF="mailto:mono-bugs%40lists.ximian.com?Subject=%5BMono-bugs%5D%20%5BBug%20542068%5D%20New%3A%20Using%20Mono2.4%20Add-On%2C%0A%20Process%20Dies%20because%20of%20Uncatchable%20exception%20during%20Ldap%20Connect%0A%20in%20MultiThreaded%20environment&In-Reply-To="
       TITLE="[Mono-bugs] [Bug 542068] New: Using Mono2.4 Add-On, Process Dies because of Uncatchable exception during Ldap Connect in MultiThreaded environment">bugzilla_noreply at novell.com
       </A><BR>
    <I>Fri Sep 25 02:54:48 EDT 2009</I>
    <P><UL>
        <LI>Previous message: <A HREF="093127.html">[Mono-bugs] [Bug 542054] MonoDevelop does not remember 'startup	project'
</A></li>
        <LI>Next message: <A HREF="093010.html">[Mono-bugs] [Bug 542068] Using Mono2.4 Add-On, Process Dies because of Uncatchable exception during Ldap Connect in MultiThreaded environment
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#93003">[ date ]</a>
              <a href="thread.html#93003">[ thread ]</a>
              <a href="subject.html#93003">[ subject ]</a>
              <a href="author.html#93003">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE><A HREF="http://bugzilla.novell.com/show_bug.cgi?id=542068">http://bugzilla.novell.com/show_bug.cgi?id=542068</A>


           Summary: Using Mono2.4 Add-On, Process Dies because of
                    Uncatchable exception during Ldap Connect in
                    MultiThreaded environment
    Classification: Mono
           Product: Mono: Runtime
           Version: 2.4.x AddOn CD
          Platform: Other
        OS/Version: Other
            Status: NEW
          Severity: Critical
          Priority: P5 - None
         Component: misc
        AssignedTo: <A HREF="http://lists.ximian.com/mailman/listinfo/mono-bugs">mono-bugs at lists.ximian.com</A>
        ReportedBy: <A HREF="http://lists.ximian.com/mailman/listinfo/mono-bugs">kuanil at novell.com</A>
         QAContact: <A HREF="http://lists.ximian.com/mailman/listinfo/mono-bugs">mono-bugs at lists.ximian.com</A>
                CC: <A HREF="http://lists.ximian.com/mailman/listinfo/mono-bugs">amahabaleshwar at novell.com</A>
          Found By: Third Party Developer/Partner


We have simulated the scenario where multiple clients try to ldap authenticate
at once and iFolder server creates a separate thread for each ldap
authentication. When load is more, then ldap throws the exception which could
not be caught by the try-catch blocks (or even the origin of exception is not
known) and ultimately whole process dies. This results in iFolder server dying
itself. 

I have attached the snippet of exceptions. There are 2 types, one shows that
there is &quot;Connect Error: &quot; and then unhandled exception comes and another is
without the connect error. 
---------------------------------------------------------------------------------------------------------
Snippet of the exception
...................
...................
...................
Verifying Password !!!
Verifying Password !!!
Connect Passed for :cn=test8,o=novell
Disconnecting the connection ..............
Connect Passed for :cn=test16,o=novell
Disconnecting the connection ..............
Connect Passed for :cn=test5,o=novell
Disconnecting the connection ..............
Verifying Password !!!
Error for User: cn=test7,o=novell
LdapExceptionError: Connect Error
Disconnecting the connection ..............
Verifying Password !!!
Connect Passed for :cn=test2,o=novell
Disconnecting the connection ..............
Connect Passed for :cn=test11,o=novell
Connect Passed for :cn=test19,o=novell
Disconnecting the connection ..............
Connect Passed for :cn=test20,o=novell
Disconnecting the connection ..............
Disconnecting the connection ..............

Unhandled Exception: System.Net.Sockets.SocketException: The socket is not
connected
  at System.Net.Sockets.Socket.Shutdown (SocketShutdown how) [0x00000]
  at Novell.Directory.Ldap.Connection.shutdown (System.String reason, Int32
semaphoreId, Novell.Directory.Ldap.InterThreadException notifyUser) [0x00000]
  at Novell.Directory.Ldap.Connection+ReaderThread.Run () [0x00000]

------------------------------------
another snippet:

Connect Passed for :cn=test7,o=novell
Disconnecting the connection ..............
Connect Passed for :cn=test16,o=novell
Disconnecting the connection ..............
Verifying Password !!!
Connect Passed for :cn=test17,o=novell
Disconnecting the connection ..............
Disconnect Exception
Verifying Password !!!
Verifying Password !!!
Verifying Password !!!
Verifying Password !!!
Verifying Password !!!
Verifying Password !!!
Verifying Password !!!
Error for User: cn=test14,o=novell
LdapExceptionError: Connect Error
Disconnecting the connection ..............

Unhandled Exception: System.Net.Sockets.SocketException: The socket is not
connected
  at System.Net.Sockets.Socket.Shutdown (SocketShutdown how) [0x00000]
  at Novell.Directory.Ldap.Connection.shutdown (System.String reason, Int32
semaphoreId, Novell.Directory.Ldap.InterThreadException notifyUser) [0x00000]
  at Novell.Directory.Ldap.Connection+ReaderThread.Run () [0x00000]

---------------------------------------------------------------------------------------------------------------------
I am not worried about the &quot;Disconnect Exception&quot; above as it is known and LDAP
team is already working on that. This socket exception is the new one which
could not be handled by any try-catch block.

In Next comment, i would attach the sample testcases and how to reproduce this
easily.

-- 
Configure bugmail: <A HREF="http://bugzilla.novell.com/userprefs.cgi?tab=email">http://bugzilla.novell.com/userprefs.cgi?tab=email</A>
------- You are receiving this mail because: -------
You are the QA contact for the bug.
You are the assignee for the bug.
</PRE>











































<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="093127.html">[Mono-bugs] [Bug 542054] MonoDevelop does not remember 'startup	project'
</A></li>
	<LI>Next message: <A HREF="093010.html">[Mono-bugs] [Bug 542068] Using Mono2.4 Add-On, Process Dies because of Uncatchable exception during Ldap Connect in MultiThreaded environment
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#93003">[ date ]</a>
              <a href="thread.html#93003">[ thread ]</a>
              <a href="subject.html#93003">[ subject ]</a>
              <a href="author.html#93003">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://lists.ximian.com/mailman/listinfo/mono-bugs">More information about the mono-bugs
mailing list</a><br>
</body></html>
