<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [Mono-list] exceptions are not thrown from ThreadPool'ed thread objects?
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:sarvesh%20%3Csarvesh.com%40gmail.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   
   <LINK REL="Previous"  HREF="023859.html">
   <LINK REL="Next"  HREF="023888.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Mono-list] exceptions are not thrown from ThreadPool'ed thread objects?
   </H1>
    <B>sarvesh
    </B> 
    <A HREF="mailto:sarvesh%20%3Csarvesh.com%40gmail.com%3E"
       TITLE="[Mono-list] exceptions are not thrown from ThreadPool'ed thread objects?">sarvesh &lt;sarvesh.com@gmail.com&gt;
       </A><BR>
    <I>Tue, 19 Oct 2004 13:39:06 +0530</I>
    <P><UL>
        <LI> Previous message: <A HREF="023859.html">[Mono-list] exceptions are not thrown from ThreadPool'ed thread objects?
</A></li>
        <LI> Next message: <A HREF="023888.html">[Mono-list] exceptions are not thrown from ThreadPool'ed
 thread objects?
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#23870">[ date ]</a>
              <a href="thread.html#23870">[ thread ]</a>
              <a href="subject.html#23870">[ subject ]</a>
              <a href="author.html#23870">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>That's the right behaviour it should not get thrown up to say the Main
Method. But what is interesting with the code is it should throw an
UnHandled exception. The code does throw unhandled exception with ms
.net but not with mono ??



On Tue, 19 Oct 2004 00:58:26 -0700, gennady wexler &lt;<A HREF="mailto:adyler@winisp.net">adyler@winisp.net</A>&gt; wrote:
&gt;<i> has anyone noticed this problem? that is if you have a ThreadPool'ed thread
</I>&gt;<i> object created, any exception thrown inside of that thread will not be
</I>&gt;<i> rethrown up at all. I ran into this accidentally while developing some
</I>&gt;<i> performance code..
</I>&gt;<i> 
</I>&gt;<i> here's an example, could someone please try this with .net compiler/runtime?
</I>&gt;<i> 
</I>&gt;<i> if you just compile and run it, the exception in _ThreadProc does not get
</I>&gt;<i> thrown.
</I>&gt;<i> 
</I>&gt;<i> now, if you uncomment regular thread definition below &quot;ThreadPool&quot; - you
</I>&gt;<i> will get &quot;exception 2&quot; get thrown.
</I>&gt;<i> 
</I>&gt;<i> any ideas? is this expected? I hope not...
</I>&gt;<i> 
</I>&gt;<i> using System;
</I>&gt;<i> using System.Threading;
</I>&gt;<i> 
</I>&gt;<i> public class main {
</I>&gt;<i>         static void Main() {
</I>&gt;<i>                 // this will not throw exception 1 (seems to be a bug?)
</I>&gt;<i>                 ThreadPool.UnsafeQueueUserWorkItem(new
</I>&gt;<i>                         WaitCallback(_ThreadProc), null);
</I>&gt;<i> 
</I>&gt;<i>                 // uncomment this to thrown exception 2 (as expected)
</I>&gt;<i>                 // new Thread(new ThreadStart(_ThreadProc2)).Start();
</I>&gt;<i> 
</I>&gt;<i>                 Thread.Sleep(90000);
</I>&gt;<i>         }
</I>&gt;<i> 
</I>&gt;<i>         private static void _ThreadProc(Object state) {
</I>&gt;<i>                 throw new Exception(&quot;exception 1&quot;);
</I>&gt;<i>         }
</I>&gt;<i> 
</I>&gt;<i>         private static void _ThreadProc2() {
</I>&gt;<i>                 throw new Exception(&quot;exception 2&quot;);
</I>&gt;<i>         }
</I>&gt;<i> }
</I>&gt;<i> 
</I>&gt;<i> _______________________________________________
</I>&gt;<i> Mono-list maillist  -  <A HREF="mailto:Mono-list@lists.ximian.com">Mono-list@lists.ximian.com</A>
</I>&gt;<i> <A HREF="http://lists.ximian.com/mailman/listinfo/mono-list">http://lists.ximian.com/mailman/listinfo/mono-list</A>
</I>&gt;<i>
</I>
</PRE>
<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI> Previous message: <A HREF="023859.html">[Mono-list] exceptions are not thrown from ThreadPool'ed thread objects?
</A></li>
	<LI> Next message: <A HREF="023888.html">[Mono-list] exceptions are not thrown from ThreadPool'ed
 thread objects?
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#23870">[ date ]</a>
              <a href="thread.html#23870">[ thread ]</a>
              <a href="subject.html#23870">[ subject ]</a>
              <a href="author.html#23870">[ author ]</a>
         </LI>
       </UL>
</body></html>
